### PR TITLE
snap

### PR DESCRIPTION
**Pull request by eslerm**
Added gomuks config for the snap package manager. Ready to be added to https://snapcraft.io/

### CODE REVIEW

**Comment by z8512** [comment]
Wtf! Who need it? Please stop packaging it into bulky,bloated snap or flatpak

**Comment by eslerm** [comment]
> Wtf! Who need it? Please stop packaging it into bulky,bloated snap or flatpak

Perhaps you could contribute by creating a PPA for Ubuntu users.

**Comment by tulir** [comment]
I don't think I'll add any more packaging stuff to the repo, that should be handled by distro maintainers.

**Comment by eslerm** [comment]
Sounds good @tulir

If you change your mind the [snapcraft build system](https://snapcraft.io/build) can automatically sync with github to maintain the snap package for many distros.

**Comment by eslerm** [comment]
@tulir I am now publishing gomuks through https://github.com/eslerm/gomuks-snap

**Pull request closed without merging**
