### PR TITLE
web/roomlist: disable text selection

### PR DESCRIPTION
**Pull request by sumnerevans**

### CODE REVIEW

**Comment by tulir** [comment]
It's already disabled in `div.room-entry`. I guess it might need `-webkit-user-select` too, but other unnecessary backwards compatibility should not be added

**Review by tulir — APPROVED** [review]
Looks right now, although I wonder if postcss would do that automatically if safari is added to targets in `vite.config.ts` :thinking:

**Comment by sumnerevans** [comment]
I tried adding `safari14` to the targets, and it did not change anything.

**Comment by tulir** [comment]
Weird, I added safari18 and it seems to have added `-webkit-user-select`s to the production build css

**Comment by tulir** [comment]
Wails seems to work fine with https://github.com/tulir/gomuks/commit/c6f8d552018e8e3bc7ef44f56ddffb3398794ece

**Pull request closed without merging**
