### PR TITLE
lib/notification: beeep for linux

### PR DESCRIPTION
**Pull request by alrs**
This changes Linux notifications to use `beeep`, which is BSD licensed.

### CODE REVIEW

**Comment by alrs** [comment]
Needs further testing, will re-open.

**Comment by alrs** [comment]
OK, I had to spin up a Debian Bullseye container in Docker to get this to build, but it's working.

**Review by tulir — COMMENTED** [review]
beeep doesn't seem to do notification sounds properly, are there any advantages to using it?

**Comment by tulir** [comment]
I guess the only relevant difference is that it tries to use dbus directly, but that part should probably just be copied over separately if it's needed.

**Pull request closed without merging**
