### PR TITLE
web/typing: render typing notifications below composer

### LINKED ISSUE #515: Render typing notifications

### PR DESCRIPTION
**Pull request by sumnerevans**
Closes #515

This PR implements rendering typing notifications below the composer. It is heavily inspired by how Discord renders typing notifications. It renders the avatar and displayname of the users that are typing up to 4 users. Once the number of users typing goes above 4, only the first 4 avatars are rendered, and the displaynames are no longer rendered.

Here are some screenshots of what it looks like:

image

As you can see, in order to implement this, I made the composer floating. This is what it looks like without any typing notifications:

I am not entirely happy with this, as I had to increase the horizontal padding of the composer and timeline to `1.6rem`, but I think that this is reasonable.

I also fixed a bug with `oxfordHumanJoin(React)?` for two-element arrays. If you don't merge this full PR, you should at least merge that commit.

### CODE REVIEW

**Comment by sumnerevans** [comment]
Ah crap, don't merge quite yet... need to figure out how to filter out own user from the typing list

image

**Comment by sumnerevans** [comment]
Also, I'm not sure how to force it to fetch the member info. It seems to only work for users that have sent a message that has been loaded.

**Comment by JadedBlueEyes** [comment]
From a design perspective, one alternative way to do this would be to have the typing indicator as an item at the bottom of the timeline. This would avoid the extra dead space below the composer - and ot would hide the typing indicator when the user is scrolled back and reading rather than participating in the conversation, although that could be a disadvantage too. 

Generally I would prefer it on top of the composer rather than below it, for multiple reasons including the spacing. 😅

Good work though! ❤️

**Comment by sumnerevans** [comment]
@JadedBlueEyes the reason I chose to put it below is because I hate the way that the timeline jumps around in Element when someone starts/stops typing, so I really wanted to avoid that. I think that there is a possible way to implement this above the composer in a way that isn't horrible, but I went with the Discord-inspired approach.

**Comment by tulir** [comment]
Hmm, maybe it'd be better to slightly increase the empty space that's always at the bottom of the timeline and render small typing indicators there

**Comment by sumnerevans** [comment]
The issue with that then the messages don't cleanly disappear directly under the composer, there's an empty padding that is always there and sometimes populated with typing indicators.

Unless you mean putting them under the composer border, but I think that just looks weird.

**Comment by tulir** [comment]
Oh right, the typing indicators would have to be a part of the timeline so they disappear when scrolling up, otherwise it'd look weird

Maybe below is fine too 🤔

**Comment by JadedBlueEyes** [comment]
My thought is to have a transparent container above the composer that gets filled with the typing indicators, so the timeline has the correct spacing below by default, and there's less impeding the viewport by default. A secondary benefit is this won't break if the typing indicator gets wider than viewport, as it will reflow and make the container taller.

**Comment by sumnerevans** [comment]
The problem with transparent above is that then the typing notifications overlap with the timeline when scrolling.

Putting it into the timeline has the downside of not being able to see typing notifications while scrolling. This is the decision that iMessage makes, but I'm not sure it makes sense for our case.

**Comment by JadedBlueEyes** [comment]
Not necessarily, the transparent container is just there for spacing. When the typing indicators are visible, the background should be visible too.

Something like
```html
<transparent-container min-height>
  <if-indicators>
    <background-container>
      <typing-indicator />
    </background-container>
  </if-indicators>
</transparent-container>
```

**Comment by sumnerevans** [comment]
Adding `box-shadow: 0 0 1rem var(--modal-box-shadow-color);` might be a good option for adding a box shadow to the composer in floating mode.

image

**Pull request merged**
